import java.util.Scanner;
public class Company Income Calculator {

    public static void main(String[] args) throws Exception {
        int [] bookings = new int [10]; //creates array bookings with 10 elements
        
        for (int a = 0; a < 10; a++) 
            bookings[a] = 0; //initializes all elements to zero
        
        System.out.print("Flight\tSeats\nNumber\tBooked\n"); //header
        printBookings(bookings, 10); //prints table of all flights while there is no bookings
        System.out.print("\n");
        
        String myfile = "flightInfo7.txt"; //data file location
        java.io.File flightInfo7 = new java.io.File (myfile); //file with data
        Scanner sc = new Scanner (flightInfo7); //scanner to read file
        
        int tr, fl, seats;
        
        while (sc.hasNext()) { //trailer
            tr = sc.nextInt(); //transaction
            fl = sc.nextInt(); //flight number
            seats = sc.nextInt(); //seats booked or canceled
            
            if (tr == 1) {
                bookings[fl] += seats; //if the transaction is 1, the number of seats will be added
                System.out.println("Log: " + seats + " seats were booked for Flight " + fl);
            }
            if (tr == 2) 
                if (seats < bookings[fl]) {
                    bookings[fl] -= seats; //if the transaction is 2, the number of seats will be subtracted
                    System.out.println("Log: " + seats + " seats were canceled for Flight " + fl);
                } //the transactions & number of seats booked and canceled will be printed for both if statements
                else System.out.println("Error: More seats were attempted to be canceled than currently booked!");
        //if more seats than currently booked are attempted to be canceled, it will reject and print the error message
        }
        System.out.print("\nFlight\tSeats\nNumber\tBooked\n"); //header for flight number and seats booked
        printBookings(bookings, 10); //calls method printBookings to print flight number and seats booked
        
        sortBookings(bookings, 10); //calls method sortBookings which will sort the array in ascending order
        
        System.out.print("\nFlight\tSeats\nNumber\tBooked\n"); //header for flight number and seats booked
        printBookings(bookings, 10); //calls method printBookings to print flight number and seats booked after sorting
        
        double total = 1.00 * Income(bookings, 10, 120); /*calls method income to get total income and makes
        it a double so that it can be in dollar format*/
        System.out.printf("\nThe total income from all the flights is $%5.2f\n", total); //prints total income  
    }    
    public static void printBookings (int [] a, int b) {
        for(int c = 0; c < b; c++) //goes through entire array
            System.out.println(c + "\t" + a[c]); //prints each element and its value 
    }
    
    public static int Income (int [] a, int b, int c) {
        int total = 0;
        for(int d = 0; d < b; d++) //goes through entire array
            total += a[d] * c; //multiplies ticket price with number of seats per flight
        
        return total; //returns total income generated by all ticket sales
    }  
    
    public static void sortBookings (int [] a, int b) { //bubble sort algorithm for sorting array bookings
        //int b is the number of elements in the array
        int c = b-1, temp; //temp is to hold the previous value whilst swapping when the array is sorting
        for (int pass = 1; pass < b; pass++) 
            for (int d = 0; d < c; d++)
                if (a[d] > a[d+1]) {
                    temp = a[d];
                    a[d] = a[d+1];
                    a[d+1] = temp;
                }
    }
}